id = "short-giraffe-theme"
name = "Short Giraffe Theme"
version = "2.2.0"
schema_version = 1
authors = ["Mehdi Hoseini <mehdi.hoseiniii@proton.me>"]
description = "A dark theme with carefully picked colors"
repository = "https://github.com/Mehdi-Hp/Short-Giraffe"
